In [ ]:
!python -m pip install tensorflow_text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 31.2 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
from google.colab import files
 
 
uploaded = files.upload()

Saving kumar.csv to kumar.csv


In [ ]:
import pandas as pd
import io
 
df = pd.read_csv(io.BytesIO(uploaded['kumar.csv']))
print(df)


    Unnamed: 0           review_title  \
0            0   Good quality product   
1            1        Worth the money   
2            2              Must buy!   
3            3         Classy product   
4            4  Mind-blowing purchase   
5            5              Wonderful   
6            6           Nice product   
7            7              Must buy!   
8            8                   Good   
9            9      Worth every penny   
10          10      Terrific purchase   
11          11              Fabulous!   
12          12            Pretty good   
13          13        Value-for-money   
14          14              Very Good   
15          15    Best in the market!   
16          16                   Nice   
17          17              Just wow!   
18          18              Fabulous!   
19          19        Waste of money!   

                                              reviews  
0   I am writing this review after 12 days of usag...  
1   Overall I'm happy with

In [ ]:
reviews_list =list(df['reviews'])

In [ ]:
reviews_list

["I am writing this review after 12 days of usage. This phone looks very decent, light weight, no heating problem, display is fine, smooth operations, charging is fast but not actually in 15 minutes. It will be 80% from 10 within 15 minutes that's for sure. And yes, vedio and sound quality is awsome. I love watching movies at this rather than my lappy. I am a little disappointed with the camera, it's just better than average. Front camera is also same. Battery backup is one day considering no...READ MORE",
 "Overall I'm happy with the phone's performance. Love the design, the display is outstanding! Much better camera and love the Dolby Atmos feature. You can clearly feel the difference when the headset is on. I felt like the camera smoothens the skin when taking photos in the direct sunlight and doesn't look natural at all.and yes the macro camera is below averageREAD MORE",
 'Amazing mobile I will give this 10/10 score for all over features. Budget friendly mobile in this price range

In [ ]:
df.groupby('reviews').describe()

Unnamed: 0                  \
                                                        count  mean std   min   
reviews                                                                         
* Positive: 1) Display is good bcoz of Oled 120...        1.0  13.0 NaN  13.0   
1. Camera is too good , I clicked all pictures ...        1.0   5.0 NaN   5.0   
5G Signal Issue on Redmi Note 12 ProI am encoun...        1.0  19.0 NaN  19.0   
After one week usesd, this one  was amazing pho...        1.0  11.0 NaN  11.0   
After purchasing and writing review. Redmi note...        1.0  15.0 NaN  15.0   
Amazing mobile I will give this 10/10 score for...        1.0   2.0 NaN   2.0   
Amit nanda- Good design and 120Hh screen is sup...        1.0  17.0 NaN  17.0   
Apart from stylish look and smooth display , no...        1.0   8.0 NaN   8.0   
Best phone .. performance is too good and displ...        1.0   3.0 NaN   3.0   
I am writing this review after 12 days of usage...        1.0   0.0 NaN   0.0   
It's not a device that would be bought at this ...        1.0  16.0 NaN  16.0   
Its feels good to hold and considerably light t...        1.0   6.0 NaN   6.0   
Nice phone. Camera is good at day time and low ...        1.0  18.0 NaN  18.0   
Overall I'm happy with the phone's performance....        1.0   1.0 NaN   1.0   
Really Awesome Smartphone By Redmi. Best price ...        1.0   4.0 NaN   4.0   
Really happy with this phone after using it for...        1.0  14.0 NaN  14.0   
Super smartphone and display osme😘,, camera ove...        1.0   9.0 NaN   9.0   
This phone is all rounder phone amazing perform...        1.0  10.0 NaN  10.0   
display is outstanding. sounds quality is very ...        1.0  12.0 NaN  12.0   
these mobile is a value for money phone Rear ca...        1.0   7.0 NaN   7.0   

                                                                            
                                                     25%   50%   75%   max  
reviews                                                                     
* Positive: 1) Display is good bcoz of Oled 120...  13.0  13.0  13.0  13.0  
1. Camera is too good , I clicked all pictures ...   5.0   5.0   5.0   5.0  
5G Signal Issue on Redmi Note 12 ProI am encoun...  19.0  19.0  19.0  19.0  
After one week usesd, this one  was amazing pho...  11.0  11.0  11.0  11.0  
After purchasing and writing review. Redmi note...  15.0  15.0  15.0  15.0  
Amazing mobile I will give this 10/10 score for...   2.0   2.0   2.0   2.0  
Amit nanda- Good design and 120Hh screen is sup...  17.0  17.0  17.0  17.0  
Apart from stylish look and smooth display , no...   8.0   8.0   8.0   8.0  
Best phone .. performance is too good and displ...   3.0   3.0   3.0   3.0  
I am writing this review after 12 days of usage...   0.0   0.0   0.0   0.0  
It's not a device that would be bought at this ...  16.0  16.0  16.0  16.0  
Its feels good to hold and considerably light t...   6.0   6.0   6.0   6.0  
Nice phone. Camera is good at day time and low ...  18.0  18.0  18.0  18.0  
Overall I'm happy with the phone's performance....   1.0   1.0   1.0   1.0  
Really Awesome Smartphone By Redmi. Best price ...   4.0   4.0   4.0   4.0  
Really happy with this phone after using it for...  14.0  14.0  14.0  14.0  
Super smartphone and display osme😘,, camera ove...   9.0   9.0   9.0   9.0  
This phone is all rounder phone amazing perform...  10.0  10.0  10.0  10.0  
display is outstanding. sounds quality is very ...  12.0  12.0  12.0  12.0  
these mobile is a value for money phone Rear ca...   7.0   7.0   7.0   7.0

In [ ]:
from google.colab import files
 
 
uploaded = files.upload()

Saving kumar1.txt to kumar1.txt


In [ ]:
file1 = open("kumar1.txt","r")

In [ ]:
print(file1.read())

I am writing this review after 12 days of usage. This phone looks very decent, light weight, no heating problem, display is fine, smooth operations, charging is fast but not actually in 15 minutes. It will be 80% from 10 within 15 minutes that's for sure. And yes, vedio and sound quality is awsome. I love watching movies at this rather than my lappy. I am a little disappointed with the camera, it's just better than average. Front camera is also same. Battery backup is one day considering no...READ MORE
Overall I'm happy with the phone's performance. Love the design, the display is outstanding! Much better camera and love the Dolby Atmos feature. You can clearly feel the difference when the headset is on. I felt like the camera smoothens the skin when taking photos in the direct sunlight and doesn't look natural at all.and yes the macro camera is below averageREAD MORE
Amazing mobile I will give this 10/10 score for all over features. Budget friendly mobile in this price range.super not

In [ ]:
with open("kumar1.txt", "r") as km:
    lines = km.readlines()
    print(lines)

["I am writing this review after 12 days of usage. This phone looks very decent, light weight, no heating problem, display is fine, smooth operations, charging is fast but not actually in 15 minutes. It will be 80% from 10 within 15 minutes that's for sure. And yes, vedio and sound quality is awsome. I love watching movies at this rather than my lappy. I am a little disappointed with the camera, it's just better than average. Front camera is also same. Battery backup is one day considering no...READ MORE\n", "Overall I'm happy with the phone's performance. Love the design, the display is outstanding! Much better camera and love the Dolby Atmos feature. You can clearly feel the difference when the headset is on. I felt like the camera smoothens the skin when taking photos in the direct sunlight and doesn't look natural at all.and yes the macro camera is below averageREAD MORE\n", 'Amazing mobile I will give this 10/10 score for all over features. Budget friendly mobile in this price ran

In [ ]:
lines

["I am writing this review after 12 days of usage. This phone looks very decent, light weight, no heating problem, display is fine, smooth operations, charging is fast but not actually in 15 minutes. It will be 80% from 10 within 15 minutes that's for sure. And yes, vedio and sound quality is awsome. I love watching movies at this rather than my lappy. I am a little disappointed with the camera, it's just better than average. Front camera is also same. Battery backup is one day considering no...READ MORE\n",
 "Overall I'm happy with the phone's performance. Love the design, the display is outstanding! Much better camera and love the Dolby Atmos feature. You can clearly feel the difference when the headset is on. I felt like the camera smoothens the skin when taking photos in the direct sunlight and doesn't look natural at all.and yes the macro camera is below averageREAD MORE\n",
 'Amazing mobile I will give this 10/10 score for all over features. Budget friendly mobile in this price r

In [ ]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)


In [ ]:
text_preprocessed = bert_preprocess_model(lines)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [ ]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(20, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 0]], dtype=int32)>

In [ ]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(20, 128), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(20, 128), dtype=int32, numpy=
array([[  101,  1045,  2572, ...,     0,     0,     0],
       [  101,  3452,  1045, ...,     0,     0,     0],
       [  101,  6429,  4684, ...,     0,     0,     0],
       ...,
       [  101, 26445,  2102, ...,     0,     0,     0],
       [  101,  3835,  3042, ...,     0,     0,     0],
       [  101,  1019,  2290, ...,  2062,   102,     0]], dtype=int32)>

In [ ]:
bert_model = hub.KerasLayer(encoder_url)

In [ ]:
bert_results = bert_model(text_preprocessed)

In [ ]:
bert_results.keys()

dict_keys(['default', 'sequence_output', 'encoder_outputs', 'pooled_output'])

In [ ]:
bert_results['sequence_output']

<tf.Tensor: shape=(20, 128, 768), dtype=float32, numpy=
array([[[ 0.03177553, -0.24096707,  0.46188223, ..., -0.25408882,
          0.62704575,  0.04462964],
        [ 0.34743336, -0.7889522 ,  0.29396072, ..., -0.17040181,
          0.93898207, -0.19753195],
        [-0.12595072, -0.12349354,  0.35574228, ..., -0.01084387,
          0.33556503,  0.2457129 ],
        ...,
        [ 0.05339681, -0.51347494,  0.55415833, ...,  0.46146703,
          0.3309683 , -0.33412644],
        [ 0.08653125, -0.49468753,  0.560868  , ...,  0.4536612 ,
          0.33858013, -0.30081987],
        [ 0.06180018, -0.60679144,  0.5757867 , ...,  0.47173342,
          0.30219954, -0.4926608 ]],

       [[ 0.13303947, -0.20824076,  0.38805974, ..., -0.31095445,
          0.23497362,  0.20746207],
        [ 0.374761  ,  0.37478316,  0.20789912, ..., -0.31112432,
          0.8190461 ,  0.10385662],
        [ 0.7166704 , -0.22088951,  0.6909165 , ..., -0.24771944,
          0.7668371 ,  0.00301036],
        ...

In [ ]:
bert_results['pooled_output']

<tf.Tensor: shape=(20, 768), dtype=float32, numpy=
array([[-0.78265876, -0.41210902, -0.9525899 , ..., -0.9017082 ,
        -0.57920665,  0.8214775 ],
       [-0.71473396, -0.2640688 , -0.8897025 , ..., -0.89993083,
        -0.51483667,  0.7863117 ],
       [-0.7891543 , -0.48703614, -0.90412986, ..., -0.8965319 ,
        -0.6348192 ,  0.811245  ],
       ...,
       [-0.6202804 , -0.4257496 , -0.9697748 , ..., -0.96368855,
        -0.41026166,  0.62683475],
       [-0.79921246, -0.5495074 , -0.9730051 , ..., -0.9547322 ,
        -0.597053  ,  0.8058573 ],
       [-0.6670743 , -0.6144906 , -0.9771546 , ..., -0.9583188 ,
        -0.70664203,  0.71662796]], dtype=float32)>

In [ ]:
len(bert_results['encoder_outputs'])

12

In [ ]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(20, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True, 

In [ ]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(20, 128, 768), dtype=float32, numpy=
 array([[[ 0.04040901, -0.03847999, -0.23941398, ...,  0.27282214,
          -0.09682442, -0.01628035],
         [ 0.221746  ,  0.34941143, -0.36554772, ...,  0.8026691 ,
           0.81109846,  0.02790656],
         [-0.2910831 , -0.15185785,  0.17184612, ...,  0.03155315,
           1.4710383 , -0.60821676],
         ...,
         [-0.20360032, -0.29447278,  0.5308631 , ...,  0.21991834,
          -0.23774415, -0.08392405],
         [-0.2965833 , -0.2831147 ,  0.42433846, ...,  0.2454011 ,
          -0.15797372, -0.15608203],
         [-0.19548872, -0.22210525,  0.44218737, ...,  0.5039464 ,
          -0.42272237, -0.18375397]],
 
        [[ 0.03412917,  0.09020297, -0.2764434 , ...,  0.2274028 ,
          -0.02047833,  0.02317818],
         [ 1.266606  ,  0.9477718 , -0.5292789 , ...,  0.826908  ,
           1.7913302 , -0.36633778],
         [-0.1100108 ,  0.60542804, -0.21205199, ...,  0.46063328,
           0.91423   ,  0.0

In [ ]:
# Transformers installation
! pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 50.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 22.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 59.7 MB/s eta 0:00:00


In [ ]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [ ]:
classifier('We are very happy to show you the  Transformers library.')

[{'label': 'POSITIVE', 'score': 0.9997994303703308}]

In [ ]:
classifier('The pizza is not that great but the crust is awesome.')

[{'label': 'POSITIVE', 'score': 0.9998461008071899}]

In [ ]:
results = classifier(["We are very happy to show you the 🤗 Transformers library.",
           "We hope you don't hate it."])
for result in results:
    print(f"label: {result['label']}, with score: {round(result['score'], 4)}")

label: POSITIVE, with score: 0.9998
label: NEGATIVE, with score: 0.5309


In [ ]:
classifier = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

In [ ]:
classifier("Esperamos que no lo odie.")
#the food is bad

[{'label': '3 stars', 'score': 0.33688199520111084}]

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [ ]:
model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
# This model only exists in PyTorch, so we use the `from_pt` flag to import that model in TensorFlow.
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
classifier("I am a good boy")

[{'label': '4 stars', 'score': 0.4229269027709961}]

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tf_model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_57']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
inputs = tokenizer("We are very happy to show you the 🤗 Transformers library.")

In [ ]:
print(inputs)

{'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [ ]:
tf_batch = tokenizer(
    ["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf"
)

In [ ]:
for key, value in tf_batch.items():
    print(f"{key}: {value.numpy().tolist()}")

input_ids: [[101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012, 102], [101, 2057, 3246, 2017, 2123, 1005, 1056, 5223, 2009, 1012, 102, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]


BERT TASK : Question and Answering


In [ ]:
!pip install transformers


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from transformers import AutoTokenizer, AutoModelForQuestionAnswering, pipeline

tokenizer= AutoTokenizer.from_pretrained('distilbert-base-cased-distilled-squad')
model= AutoModelForQuestionAnswering.from_pretrained('distilbert-base-cased-distilled-squad')

context = "When a lion was resting in the jungle, a mouse began racing up and down his body for amusement. The lion’s sleep was interrupted, and he awoke enraged. The lion was going to eat the mouse when the mouse begged him to let him go. “I assure you, if you save me, I will be of immense help to you in the future.” The lion laughed at the mouse’s self-assurance and freed him. A group of hunters arrived in the forest one day and captured the lion. They had him tied to a tree. The lion began to roar as he struggled to get out. Soon, the mouse passed by and spotted the lion in distress. He dashed off, biting on the ropes to free the lion, and the two hurried off into the woods."
#context1 = "Life is game, Just enjoy each and every movement"
question1 = "What is moral of the story?"
question2 = "who was resting in the forest?"
question3 = 'who disturbed the lion?'
question4 = "who begged for the life?"
question5 = "What is the promise of mouse?"
question6 = "who was the people?"
question7 = "was the lion saved?"


In [ ]:
nlp = pipeline('question-answering', model=model, tokenizer=tokenizer)
result = nlp(question=question3, context=context)
print(result)

{'score': 0.18528397381305695, 'start': 39, 'end': 46, 'answer': 'a mouse'}


In [ ]:
pip install rake-nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install flair

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 373.1/373.1 kB 6.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 71.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 69.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 58.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 26.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.5/788.5 kB 51.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
pip install streamlit

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 34.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 22.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 86.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 18.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.3 MB/s eta 0:00:00
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=41190c48eac40f44209dff4b2ec2dc9532007f810fb2d279c5635e43f007c805
  Stored in directory: /root/.cache/pip/wheels/2d/f0/a8/1094fca7a7e5d0d12ff56e0c64675d72aa5cc81a5fc200e849
Successfully built validators


In [ ]:
from google.colab import files
 
 
uploaded = files.upload()

Saving kumar.csv to kumar.csv


In [ ]:
import pandas as pd
import io
 
df = pd.read_csv(io.BytesIO(uploaded['kumar.csv']))
print(df)


    Unnamed: 0           review_title  \
0            0   Good quality product   
1            1        Worth the money   
2            2              Must buy!   
3            3         Classy product   
4            4  Mind-blowing purchase   
5            5              Wonderful   
6            6           Nice product   
7            7              Must buy!   
8            8                   Good   
9            9      Worth every penny   
10          10      Terrific purchase   
11          11              Fabulous!   
12          12            Pretty good   
13          13        Value-for-money   
14          14              Very Good   
15          15    Best in the market!   
16          16                   Nice   
17          17              Just wow!   
18          18              Fabulous!   
19          19        Waste of money!   

                                              reviews  
0   I am writing this review after 12 days of usag...  
1   Overall I'm happy with

In [ ]:
from google.colab import files
 
 
uploaded = files.upload()

Saving kumar1.txt to kumar1.txt


In [ ]:
file1 = open("kumar1.txt","r")

In [ ]:
print(file1.read())

I am writing this review after 12 days of usage. This phone looks very decent, light weight, no heating problem, display is fine, smooth operations, charging is fast but not actually in 15 minutes. It will be 80% from 10 within 15 minutes that's for sure. And yes, vedio and sound quality is awsome. I love watching movies at this rather than my lappy. I am a little disappointed with the camera, it's just better than average. Front camera is also same. Battery backup is one day considering no...READ MORE
Overall I'm happy with the phone's performance. Love the design, the display is outstanding! Much better camera and love the Dolby Atmos feature. You can clearly feel the difference when the headset is on. I felt like the camera smoothens the skin when taking photos in the direct sunlight and doesn't look natural at all.and yes the macro camera is below averageREAD MORE
Amazing mobile I will give this 10/10 score for all over features. Budget friendly mobile in this price range.super not

In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from rake_nltk import Rake
from flair.models import TextClassifier
from flair.data import Sentence
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import spacy
import pandas as pd
import string
import time



nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('vader_lexicon')

stop_words = set(stopwords.words('english'))

def read_data(data,y):
    data['lemmatized_text'] = data[y].apply(lambda x: lemmatize(x))
    data['tokenized_text'] = data[y].apply(lambda x: tokenize(x))
    data['stemmed_text'] = data[y].apply(lambda x: stemming(x))
    data['entities'] = data[y].apply(lambda x: entities(x))
    data['keywords'] = data[y].apply(lambda x: keyword(x))
    data['Sentiment'] = data[y].apply(lambda x: sentiment(x))
    data['Aspect Terms'] = data[y].apply(lambda x: aspect_extraction(x))
    return data

def read_text(data):
    with open(data, "r") as km:
      lines = km.readlines()
      for i in lines:
        print(lemmatize(i))
        print(tokenize(i))
        print(stemming(i))
        print(entities(i))
        print(keyword(i))
        print(sentiment(i))
        print(aspect_extraction(i))

    
    

def tokenize(text):
    tokens =  list(word_tokenize(text.lower()))
    tokens = [token for token in tokens if token not in stop_words]
    return tokens
    
def lemmatize(text):
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    lemmatized = " ".join([token.lemma_ for token in doc if not token.is_stop and token.text not in string.punctuation])
    return lemmatized

def stemming(text):
    ps = PorterStemmer()
    tokens = nltk.word_tokenize(text)
    stems = " ".join([ps.stem(token) for token in tokens if token not in stop_words and token not in string.punctuation])
    return stems

def entities(text):
    nlp = spacy.load('en_core_web_sm')
    doc = nlp(text)
    entities = []
    labels = []
    for ent in doc.ents:
        if ent.text not in stop_words:
            entities.append(ent.text)
            labels.append(ent.label_)
    return dict(zip(entities, labels))


def keyword(text):
    r = Rake()
    r.extract_keywords_from_text(text)
    keywords = r.get_ranked_phrases()[:10]
    return keywords

def sentiment(text):
    sia = TextClassifier.load('en-sentiment')
    sentence = Sentence(text)
    sia.predict(sentence)
    score = sentence.labels[0]
    if "POSITIVE" in str(score):
        return "Positive"
    elif "NEGATIVE" in str(score):
        return "Negative"
    else:
        return "Neutral"

tokenizer_1 = AutoTokenizer.from_pretrained("kevinscaria/ate_tk-instruct-base-def-pos-neg-neut-combined")
model_1 = AutoModelForSeq2SeqLM.from_pretrained("kevinscaria/ate_tk-instruct-base-def-pos-neg-neut-combined")
bos_instruction = """Definition: The output will be the aspects (both implicit and explicit) which have an associated opinion that are extracted from the input text. In cases where there are no aspects the output should be noaspectterm.
 keyboard
    Neutral example 1-
    input: I took it back for an Asus and same thing- blue screen which required me to remove the battery to reset.
    output: battery
    Neutral example 2-
    input: Night   Positive example 1-
    input: I charge it at night and skip taking the cord with me because of the good battery life.
    output: battery life
    Positive example 2-
    input: I even got my teenage son one, because of the features that it offers, like, iChat, Photobooth, garage band and more!.
    output: features, iChat, Photobooth, garage band
    Negative example 1-
    input: Speaking of the browser, it too has problems.
    output: browser
    Negative example 2-
    input: The keyboard is too slick.
    output: ly my computer defrags itself and runs a virus scan.
    output: virus scan
    Now complete the following example-
    input: """

def aspect_extraction(text):
  aspect_terms = []
  delim_instruct = ''
  eos_instruct = ' \noutput:'


  tokenized_text_1 = tokenizer_1(bos_instruction + text + delim_instruct + eos_instruct, return_tensors="pt")
  output_1 = model_1.generate(tokenized_text_1.input_ids)
  aspect_terms.append(tokenizer_1.decode(output_1[0], skip_special_tokens=True))
  return aspect_terms
    
def call(df,col_name):

    
    processed_df=read_data(df,col_name)
    return(processed_df)

col_name = input('enter the column name')
start = time.time()
df_processed = call(df,col_name)
end = time.time()
diff = end-start
print("the time taken of this process per seconds =",diff)
print(df_processed)


    




[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


enter the column namereviews


/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:1313: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


the time taken of this process per seconds = 119.94326758384705
    Unnamed: 0           review_title  \
0            0   Good quality product   
1            1        Worth the money   
2            2              Must buy!   
3            3         Classy product   
4            4  Mind-blowing purchase   
5            5              Wonderful   
6            6           Nice product   
7            7              Must buy!   
8            8                   Good   
9            9      Worth every penny   
10          10      Terrific purchase   
11          11              Fabulous!   
12          12            Pretty good   
13          13        Value-for-money   
14          14              Very Good   
15          15    Best in the market!   
16          16                   Nice   
17          17              Just wow!   
18          18              Fabulous!   
19          19        Waste of money!   

                                              reviews  \
0   I am writing 